# Layer 1: Trail Processing Configuration
# This file contains settings for trail network processing and cleanup

# Version Information
version: "1.10.6"

# ========================================
# LAYER 1: TRAILS - Trail network processing
# ========================================
layer1_trails:
  # Service configuration flags (matching test script exactly)
  services:
    # Core splitting services
    runEndpointSnapping: false                    # Step 1: EndpointSnappingService - DISABLED (requires Layer 2 routing_nodes)
    runTrailEndpointSnapping: true                # Step 1b: TrailEndpointSnappingService - NEW (works with trail endpoints)
    runProximitySnappingSplitting: true           # Step 2: ProximitySnappingSplittingService
    runTrueCrossingSplitting: true               # Step 1b: TrueCrossingSplittingService (X-intersections)
    runMultipointIntersectionSplitting: true     # Step 1: NEW ATOMIC TRANSACTION APPROACH - RUN FIRST
    runEnhancedIntersectionSplitting: true       # Step 5: EnhancedIntersectionSplittingService
    runTIntersectionSplitting: true              # Step 6: TIntersectionSplittingService
    runShortTrailSplitting: false                # Step 7: ShortTrailSplittingService (ModularSplittingOrchestrator)
    runIntersectionBasedTrailSplitter: true      # Step 8: IntersectionBasedTrailSplitter
    runYIntersectionSnapping: true               # Step 9: YIntersectionSnappingService
    runVertexBasedSplitting: false               # Step 10: VertexBasedSplittingService - DISABLED
    runMissedIntersectionDetection: true         # Step 11: MissedIntersectionDetectionService
    runSimpleTrailSnapping: true                 # Step 11b: SimpleTrailSnappingService (efficient snapping without splitting)
    runStandaloneTrailSplitting: true            # Step 12: StandaloneTrailSplittingService
    runDegree2Merger: true                       # Step 13: Degree2MergerService - Merge degree-2 intersections
    
    # Service parameters (matching test script)
    toleranceMeters: 5.0                         # Tolerance for spatial operations (5m for endpoint snapping)
    tIntersectionToleranceMeters: 3.0            # Tolerance for T-intersections
    yIntersectionToleranceMeters: 10.0           # Tolerance for Y-intersections
    shortTrailMaxLengthKm: 0.5                   # Max length for short trail splitting
    minSegmentLengthMeters: 5.0                  # Minimum segment length (reduced to match working JavaScript script)
    
    # Degree-2 merger parameters
    degree2MergeTolerance: 0.0                   # Distance tolerance in meters for merging (0 = no tolerance)
    degree2MinSegmentLength: 0.0                 # Minimum length for segments to be merged (0 = no minimum)
    degree2PreserveTrailNames: true              # Whether to preserve original trail names in merged segments
  # Trail cleanup and validation
  cleanup:
    minTrailLengthMeters: 0.1               # Minimum trail length to keep
    removeInvalidGeometries: true           # Remove trails with invalid geometries
    removeZeroLengthTrails: true            # Remove trails with zero length
  
  # Trail intersection detection and splitting
  intersectionDetection:
    enabled: true                           # ENABLED: Enhanced to detect multi-point intersections
    tIntersectionToleranceMeters: 3         # Tolerance for T-intersection detection (endpoint to trail)
    trueIntersectionToleranceMeters: 2      # Tolerance for true geometric intersections (increased to 2m)
    endpointNearMissToleranceMeters: 3      # Tolerance for endpoint-to-endpoint near misses
    multiPointIntersectionSupport: true     # NEW: Supports ST_MultiPoint intersections (1, 2, or more points)
    intersectionTypes: ['ST_Point', 'ST_MultiPoint']  # NEW: Detects both single and multi-point intersections
  
  # Trail gap fixing configuration
  gapFixing:
    enabled: false                          # DISABLED: Prevent artificial connector trails
    minGapDistanceMeters: 1                 # Minimum gap distance to consider (ignore very small gaps)
    maxGapDistanceMeters: 30                # Maximum gap distance to fix (extend trails to meet)
    # DISABLED: No artificial connectors to avoid network complexity
  
  # Overpass API backfill configuration
  overpassBackfill:
    enabled: false                          # DISABLED: Query Overpass API to add missing trails
    timeoutSeconds: 30                      # Timeout for Overpass API requests
    maxTrailsPerRequest: 1000               # Maximum trails to process per bbox
    # Trail types to include from Overpass API
    trailTypes:
      - "path"                              # Unpaved paths
      - "footway"                           # Footways (unpaved)
      - "track"                             # Tracks (unpaved)
      - "bridleway"                         # Bridleways
      - "steps"                             # Steps/stairs
    # Surface types to exclude (paved trails)
    excludeSurfaces:
      - "paved"
      - "asphalt"
      - "concrete"
  
  # Trail deduplication
  deduplication:
    enabled: true                           # ENABLED: Remove duplicate trails
    overlapThreshold: 0.8                   # 80% overlap threshold for considering trails duplicate
    distanceThreshold: 5                    # 5m distance threshold for very close trails
    preserveLongestTrail: true              # Keep the longest trail when duplicates found

  # Layer processing timeout (in milliseconds)
  timeout:
    processingTimeoutMs: 600000             # 10 minutes for Layer 1 trail processing
